### ISSUE TITLE
Auto-update breaks package managers

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#1508]
> Please describe what you were doing when this error happened.

Opening the computer.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 10.0.18363
Uptime: 4 days, 22 hours, 49 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Roamed
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 17124MiB / 24519MiB
```

```yaml
Name: ipfs-desktop
Description: A desktop client for IPFS.
Version: 0.11.2
Website: https://github.com/ipfs-shipyard/ipfs-desktop
License: MIT (https://spdx.org/licenses/MIT.html)
Manifest:
  C:\Users\natob\scoop\buckets\extras\bucket\ipfs-desktop.json
Installed:
  C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2 *global*
```

```yaml
go-ipfs version: 0.6.0-dev
Repo version: 9
System version: amd64/windows
Golang version: go1.14.3
```

**Error**

![image](https://user-images.githubusercontent.com/10495562/82223410-a1a8f900-98f0-11ea-9021-1a6c3aa5c5ca.png)

![image](https://user-images.githubusercontent.com/10495562/82223450-af5e7e80-98f0-11ea-9377-b64b31887349.png)

```typescript
TypeError: stopIpfs is not a function
    at quitAndInstall (C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2\resources\app.asar\src\auto-updater\quit-and-install.js:13:24)
    at Immediate.<anonymous> (C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2\resources\app.asar\src\auto-updater\index.js:87:9)
    at processImmediate (internal/timers.js:439:21)
```

**Related**

https://github.com/ipfs-shipyard/ipfs-desktop/issues/691, https://github.com/lukesampson/scoop-extras/issues/1597
