### ISSUE TITLE
Auto update not working on Windows when installed globally for all users

### ISSUE THREAD

**Issue by demdante** [ipfs-shipyard/ipfs-desktop#1514]
- OS: Windows 10
 - Version of IPFS Desktop [e.g. 0.11.2]

**Describe the bug**
I have noticed that, the last two times that IPFS-desktop has updated using the internal update functionality (when the app says a new version is available and to click button to close IPFS-desktop and install the updated version), the old version of ipfs-desktop successfully uninstalls the old version, but does not install the new version **correctly.**  I should note that I install IPFS-desktop so that it available for all users, not just the currently running user, which I think is the main reason the auto-update might be failing.  There are a few reasons that I can think of that might be the cause:

1. In my case, when I installed IPFS, I installed it so that it would be available for all users.  As you may know, this is not the default configuration for the installer (the default being to install IPFS-desktop only for the current user), so what **MAY** be happening is that IPFS-desktop is uninstalling the old version located in Program files (the folder to install app for all users), but then installing the new version in app data (only install for current user).  If this turns out to be the case, while technically still successfully installing the application (which is why I emphasized "correctly"), my IPFS-desktop Desktop icon can no longer find its source executable, and I just end up downloading the installer and reinstalling the application manually anyway, defeating the auto update functionality entirely.  This is unlikely the cause.
2. The process initiating that auto-update functionality may not have the elevated permissions that it needs to write to the Program files directory.  If the installer takes into account the install settings from the previous installation (in other words, installs the new version for all users if the previous install was configured to be installed for all users), then the reason that it might be failing is because the process may lack the elevated permissions needed to write to the Program Files directory.  I am confident that this is the cause of the failed installation, as, when I navigated to %USERNAME%\appdata\local\ipfs-desktop-updater\pending and opened the update-info.json file, I saw the following:

![image](https://user-images.githubusercontent.com/64720591/82250815-b363be00-993b-11ea-9794-f5c9271ac20d.png)

**To Reproduce**
1. Install ipfs-desktop version 0.11.2 or 0.11.1 and configure the installation so that the application is available to all users
2. Launch the application
3. Wait for the auto-update functionality dialog box to appear and initiate the process

**Expected behavior**
IPFS auto-update functionality would automatically re-install the application successfully with the same configurations as the previous install

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4646202/error.log)

**Comment by jessicaschilling** [comment]
@lidel and/or @rafaelramalho19, are you able to look into this, please?

(FWIW, but likely not relevant, I'm on a Mac and multi-user installation has upgraded as such successfully.)

**Comment by TheMageKing** [comment]
I ran into the same issue.  I got a request to grant IPFS elevated permissions, but when I hit the restart button, the contents of ProgramFiles/IPFSDesktop were all removed, and so the shortcut broke.

I'm gonna have to reinstall, and hope it finds the datastore

**Comment by demdante** [comment]
Hey.  Just a heads up.  I saw that a new version of the application was recently released and I initiated the auto update process, but the same behavior occurred again.  The application uninstalled and cleared the files from the installation directory in program files, but failed to re-install: breaking the desktop shortcut and requiring a manual re-installation.

**Comment by TheMageKing** [comment]
Happened again on this update

**Comment by lidel** [comment]
Thank you for letting us know @TheMageKing!

@rafaelramalho19 I believe this is the upstream bug described in https://github.com/electron-userland/electron-builder/issues/4815

We could detect running on Windows and implement workaround described in https://github.com/electron-userland/electron-builder/issues/4815#issuecomment-606613523 (others already shipped it, for example [this app here](https://github.com/tutao/tutanota/pull/1951/files#diff-f89305fcc1c47d7eb79f38838b54ae1fR73))

---

For future reference, the current Windows (NSIS installer) config in `electron-builder.yml`:

```
nsis:                                                                                                                                     
  include: assets/build/nsis.nsh                                                                                                          
  oneClick: false                                                                                                                         
  warningsAsErrors: false                                                                                                                 
  perMachine: false                                                                                                                       
  allowToChangeInstallationDirectory: true  
```

[nsis docs](https://www.electron.build/configuration/nsis) for  relevant options:

> * `perMachine` = `false` Boolean - Whether to show install mode installer page (choice per-machine or per-user) for assisted installer. Or whether installation always per all users (per-machine).
>   * If `oneClick` is `true` (default): Whether to install per all users (per-machine).
>   * If `oneClick` is `false` and `perMachine` is `true`: no install mode installer page, always install per-machine.
>   * If `oneClick` is `false` and `perMachine` is `false` (default): install mode installer page.
> 
> * `allowElevation` = `true` Boolean - assisted installer only. Allow requesting for elevation. If false, user will have to restart installer with elevated permissions.
> 
> * `packElevateHelper` = `true` Boolean - Whether to pack the elevate executable (required for electron-updater if per-machine installer used or can be used in the future). Ignored if perMachine is set to true.


We are missing `allowElevation` and `packElevateHelper`: the default values should be ok, but we should add explicit valies to the config, just to be safe.
