### ISSUE TITLE
Can't launch on Ubuntu 18.10 : Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#675]
Hello! I just installed the `.deb` and I tried to run it.

![image](https://user-images.githubusercontent.com/10495562/47829277-f0b62a00-dd5c-11e8-904a-28e80c7b9359.png)

System info :
```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-10-generic 
Uptime: 4 hours, 11 mins 
Packages: 2076 (dpkg), 41 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 5184MiB / 7921MiB 
```
