### ISSUE TITLE
Can't build on Ubuntu 18.10 : Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#676]
Hello! I tried to build it and it failed.

I ran exactly these commands : 

```bash
git clone https://github.com/ipfs-shipyard/ipfs-desktop.git
cd ipfs-desktop
npm install
npm start
```

Here's the errors : 

```log
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-aegir@1.0.1 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN You are using a pre-release version of node and things may not work as expected
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macos-alias@0.2.11 (node_modules/macos-alias):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macos-alias@0.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 35176 packages in 13.15s
found 13 vulnerabilities (6 low, 6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

```log
> ipfs-desktop@0.5.0 start /home/nato/Documents/GitHub/ipfs-desktop
> electron-forge start

✖ Checking your system

An unhandled error has occurred inside Forge:
Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
    at warnIfPackageManagerIsntAKnownGoodVersion (/home/nato/Documents/GitHub/ipfs-desktop/node_modules/electron-forge/dist/util/check-system.js:98:33)
    at /home/nato/Documents/GitHub/ipfs-desktop/node_modules/electron-forge/dist/util/check-system.js:44:9
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-desktop@0.5.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-desktop@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nato/.npm/_logs/2018-11-01T02_40_15_938Z-debug.log
```

System info : 

```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-10-generic 
Uptime: 4 hours, 19 mins 
Packages: 2076 (dpkg), 41 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 4721MiB / 7921MiB
```

NPM : 

```json
{
	"npm": "6.4.1",
	"ares": "1.14.0",
	"cldr": "34.0",
	"http_parser": "2.8.0",
	"icu": "63.1",
	"modules": "67",
	"napi": "3",
	"nghttp2": "1.34.0",
	"node": "12.0.0-nightly20181031d690a87b8c",
	"openssl": "1.1.0i",
	"tz": "2018e",
	"unicode": "11.0",
	"uv": "1.23.2",
	"v8": "7.0.276.32-node.7",
	"zlib": "1.2.11"
}
```
