### ISSUE TITLE
Wonky after reboot/ran out of battery 

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-desktop#792]
Please describe what you were doing when this error happened.

My laptop ran out of battery, when it rebooted it gave me the message to report an error

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: net::ERR_NETWORK_CHANGED
    at GitHubProvider.getLatestVersion (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
    at _callee$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:52:44)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at _checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:64:24)
    at checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:38:24)
    at _callee2$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:96:13)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
Thanks @daviddias. It seems to be a network error, although we don't want it to crash the app. And it's also related to our auto-updater which doesn't yet work on macOS, nor Linux, nor Windows "all-pc" install.

**Comment by olizilla** [comment]
A data point... the 0.6.1 release is missing the `.dmg` file from the assets list. The `.dmg.blockmap` file is there, but no `.dmg`

<img width="1004" alt="screenshot 2019-01-17 at 14 49 33" src="https://user-images.githubusercontent.com/58871/51326472-210d8a80-1a67-11e9-89b9-49d7013f34ea.png">

See: https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.6.1

The 0.6.0 release has both. The 0.6.1 release `latest-mac.yml` that is used by the update process to find the files it needs to do the update refers to the `ipfs-desktop-0.6.1.dmg` file, but it's not there.

```yaml
version: 0.6.1
files:
  - url: ipfs-desktop-0.6.1-mac.zip
    sha512: /axsNlTHb1o9YitxN0npbbbcHP9iDXZlDGEee3LdWyK/wPM5Q+r4kmYjh/9gXz40Ac3cT7KLOwic5EjnJGrcSA==
    size: 97740403
    blockMapSize: 102589
  - url: ipfs-desktop-0.6.1.dmg
    sha512: +z0wPoIZTs0n6XlcR82dl7H8fOBu7IhMvXkAspORAAArwYid9Z6gbju1y5iRpLXRs8f7RqM7xzZ7KWn1fgRCMw==
    size: 100987237
path: ipfs-desktop-0.6.1-mac.zip
sha512: /axsNlTHb1o9YitxN0npbbbcHP9iDXZlDGEee3LdWyK/wPM5Q+r4kmYjh/9gXz40Ac3cT7KLOwic5EjnJGrcSA==
releaseDate: '2019-01-03T17:03:56.907Z'
```

I need to dig in to why it hasn't been attached from the travis CI build.
