### ISSUE TITLE
Can't access UI in Elementary OS

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#890]
#### Versions

* `ipfs-desktop_0.7.2_amd64.deb`
* `ipfs-desktop_0.7.2_amd64.snap`

#### Operating System

```yaml
OS: elementary OS 5.0 Juno x86_64 
Kernel: 4.15.0-47-generic 
Uptime: 3 hours, 24 mins 
Packages: 2323 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: Elementary [GTK3] 
Icons: Elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3920MiB / 7920MiB 
```

#### Problem

Elementary OS doesn't have a system tray. It was previously there : 

![image](https://user-images.githubusercontent.com/10495562/55195047-b6bd4880-5181-11e9-9f09-89140e48fc05.png)

When starting the program, it briefly flashes in the dock, but I don't have any right-click option on it.

![image](https://user-images.githubusercontent.com/10495562/55194627-aa84bb80-5180-11e9-8297-b134cb1d6e48.png)

#### What should happen

When starting the program after starting it once, I should be able to see the WebUI.

#### What happened

Instead, it just checks if there's another instance of `ipfs-desktop` then closes itself. Thus, I can't access the WebUI from IPFS-Desktop.

#### Other

Using IPFS Companion, I can confirm that the node was started.

![image](https://user-images.githubusercontent.com/10495562/55194496-39dd9f00-5180-11e9-8a21-53f8c44e0616.png)
